CFLAGS:=$(CFLAGS) -g
LDFLAGS:=$(CFLAGS) -g
%.c %.h &: %.fut
	futhark c --library $<

day1: day1.o day1_fut.o day1_fut.h
	$(CC) $(LDFLAGS) -o day1 day1.o day1_fut.o

day1.o: day1.c day1_fut.h

day2: day2.o day2_fut.o day2_fut.h
	$(CC) $(LDFLAGS) -o day2 day2.o day2_fut.o

day2.o: day2.c day2_fut.h

day3: day3.o day3_fut.o day3_fut.h
	$(CC) $(LDFLAGS) -o day3 day3.o day3_fut.o

day3.o: day3.c day3_fut.h

day4: day4.o day4_fut.o day4_fut.h
	$(CC) $(LDFLAGS) -o day4 day4.o day4_fut.o

day4.o: day4.c day4_fut.h

day5: day5.o day5_fut.o day5_fut.h
	$(CC) $(LDFLAGS) -o day5 day5.o day5_fut.o

day5.o: day5.c day5_fut.h

day6: day6.o day6_fut.o day6_fut.h
	$(CC) $(LDFLAGS) -o day6 day6.o day6_fut.o

day6.o: day6.c day6_fut.h

day7: day7.o day7_fut.o day7_fut.h
	$(CC) $(LDFLAGS) -o day7 day7.o day7_fut.o

day7.o: day7.c day7_fut.h

day8: day8.o day8_fut.o day8_fut.h
	$(CC) $(LDFLAGS) -o day8 day8.o day8_fut.o

day8.o: day8.c day8_fut.h

day9: day9.o day9_fut.o day9_fut.h
	$(CC) $(LDFLAGS) -o day9 day9.o day9_fut.o

day9.o: day9.c day9_fut.h

day10: day10.o day10_fut.o day10_fut.h
	$(CC) $(LDFLAGS) -o day10 day10.o day10_fut.o

day10.o: day10.c day10_fut.h

day11: day11.o day11_fut.o day11_fut.h
	$(CC) $(LDFLAGS) -o day11 day11.o day11_fut.o

day11.o: day11.c day11_fut.h

day12: day12.o day12_fut.o day12_fut.h
	$(CC) $(LDFLAGS) -o day12 day12.o day12_fut.o

day12.o: day12.c day12_fut.h

day13: day13.o day13_fut.o day13_fut.h
	$(CC) $(LDFLAGS) -o day13 day13.o day13_fut.o

day13.o: day13.c day13_fut.h

day14: day14.o day14_fut.o day14_fut.h
	$(CC) $(LDFLAGS) -o day14 day14.o day14_fut.o

day14.o: day14.c day14_fut.h

day15: day15.o day15_fut.o day15_fut.h
	$(CC) $(LDFLAGS) -o day15 day15.o day15_fut.o

day15.o: day15.c day15_fut.h

day16: day16.o day16_fut.o day16_fut.h
	$(CC) $(LDFLAGS) -o day16 day16.o day16_fut.o

day16.o: day16.c day16_fut.h

day17: day17.o day17_fut.o day17_fut.h
	$(CC) $(LDFLAGS) -o day17 day17.o day17_fut.o

day17.o: day17.c day17_fut.h

day18: day18.o day18_fut.o day18_fut.h
	$(CC) $(LDFLAGS) -o day18 day18.o day18_fut.o

day18.o: day18.c day18_fut.h

day19: day19.o day19_fut.o day19_fut.h
	$(CC) $(LDFLAGS) -o day19 day19.o day19_fut.o

day19.o: day19.c day19_fut.h

day20: day20.o day20_fut.o day20_fut.h
	$(CC) $(LDFLAGS) -o day20 day20.o day20_fut.o

day20.o: day20.c day20_fut.h
